CREATE TABLE departamento (id int(11) PRIMARY KEY AUTO_INCREMENT, nombre varchar(50) NOT NULL UNIQUE);
CREATE TABLE empleado (id int(11) PRIMARY KEY AUTO_INCREMENT, nombre varchar(100) NOT NULL, salario decimal(10,2) DEFAULT NULL, departamento int(11) DEFAULT NULL, FOREIGN KEY (departamento) REFERENCES departamento(id) ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE proyecto (id int(11) PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(50) NOT NULL UNIQUE);
CREATE TABLE proyecto_empleado(id int(11) PRIMARY KEY AUTO_INCREMENT, id_empleado int(11) DEFAULT NULL,  id_proyecto int(11) DEFAULT NULL, FOREIGN KEY (id_empleado) REFERENCES empleado(id) ON DELETE RESTRICT ON UPDATE CASCADE,FOREIGN KEY (id_proyecto) REFERENCES proyecto(id) ON DELETE RESTRICT ON UPDATE CASCADE);
